name: Safe Commit Counter

# Workflow trigger events
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # දිනපතා එක වරක් ධාවනය වේ

# Workflow permissions
permissions:
  contents: read

jobs:
  count-commits:
    runs-on: ubuntu-latest
    timeout-minutes: 5 # Workflow එක විනාඩි 5කට වඩා ධාවනය නොවේ

    steps:
      # Repository checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Commit ගණන ගණනය කිරීම
      - name: Count commits
        run: |
          echo "Counting commits..."
          COMMIT_COUNT=$(git rev-list --count HEAD)
          echo "Total commits: $COMMIT_COUNT"

          # High commit count එකකදී delay එකතු කිරීම
          if [ "$COMMIT_COUNT" -gt 100 ]; then
            echo "High commit count detected, adding delay..."
            sleep 2
          fi

      # Optional: GitHub API භාවිතය
      - name: Check repository details
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching repo details with rate limit awareness..."
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }} > repo.json
          sleep 1 # API call එකකින් පසු delay

      # Error handling
      - name: Notify on failure
        if: failure()
        run: |
          echo "Workflow failed! Check logs for details."
